-- This migration was superseded by 20260520000001_log_dedup_unique_index.
-- It is intentionally a no-op so that the rolled-back entry in _prisma_migrations
-- can be resolved cleanly on the next deploy.
