apiVersion: 1

datasources:
  - name: Prometheus
    uid: pow-prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: true
    editable: true

  - name: Loki
    uid: pow-loki
    type: loki
    access: proxy
    url: http://127.0.0.1:3100
    editable: true
